[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# disable SMODS save conversion for AP files
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''function convert_save_data()'''
position = "after"
payload = '''if isAPProfileLoaded and isAPProfileLoaded() then return nil end'''
match_indent=true

# save run serverside
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''if G.FILE_HANDLER.run then'''
position = "after"
payload = '''if isAPProfileLoaded() then 
	G.AP.server_save_run(G.ARGS.save_run) 
	G.SAVED_GAME = G.ARGS.save_run
end'''
match_indent=true